var stockNames = [
    "Mol Global Inc.",
    "Digital Ally",
    "Image Sensing Systems",
    "Spansion Inc",
    "Viggle Inc.",
    "Shoe Carnival",
    "Cypress Semiconductor Corp",
    "Ring Energy Inc",
    "Idera Pharmaceuticals",
    "Avanir Pharmaceuticals Inc",
    "Immune Pharmaceuticals Inc.",
    "Digimarc Corp",
    "ANI Pharmaceuticals Inc",
    "Valero Energy Partners LP",
    "Pozen Inc",
    "Lakeland Industries",
    "Callon Petroleum Company",
    "Alpha Pro Tech",
    "Aerie Pharmaceuticals Inc",
    "Taser International",
    "North Atlantic Drilling Ltd. Co",
    "Jd.Com Inc.",
    "Covisint Corp",
    "Dycom Industries",
    "E2Open Inc",
    "Memorial Production Partners LP",
    "Greenbrier Companies",
    "Seadrill Partners Llc",
    "Tg Therapeutics",
    "Phillips 66 Partners LP",
    "Planar Systems",
    "Sequenom Inc",
    "Ptc Therapeutics Inc",
    "Karyopharm Therapeutics Inc",
    "Englobal Corp",
    "Shell Midstream Partners L.P.",
    "Tetraphase Pharmaceuticals Inc",
    "Amyris Inc",
    "Enphase Energy Inc",
    "Dynavax Technologies Corp",
    "Ev Energy Partners L.P.",
    "Magnum Hunter Resources Corp",
    "Atlas Pipeline Partners L.P.",
    "Nanometrics Inc",
    "The Bancorp",
    "Truecar Inc.",
    "Energy Xxi [Bermuda] Limited",
    "Turquoise Hill Resources Ltd",
    "Sportsman'S Warehouse Holdi",
    "Teekay Shipping Corp",
    "Flamel Technologies S.A.",
    "Magal Security Systems Ltd",
    "China Life Insurance Company Limited",
    "Textura Corp",
    "Raptor Pharmaceutical",
    "Limelight Networks",
    "Omnivision Technologies",
    "Fmsa Holdings Inc",
    "Harte-Hanks",
    "Dominion Midstream Partners LP",
    "Enable Midstream Partners LP",
    "Coherus Biosciences Inc.",
    "Breitburn Energy Partners L.P.",
    "Western Refining",
    "Sophiris Bio Inc",
    "Achillion Pharmaceuticals",
    "Sky-Mobi Limited",
    "Renewable Energy Group Inc",
    "Golar Lng Partners LP",
    "Noah Holdings Ltd",
    "Boardwalk Pipeline Partners L.P.",
    "Nevro Corp",
    "Ligand Pharmaceuticals Inc",
    "Biogen Idec Inc",
    "Oneok Partners L.P.",
    "Idreamsky Technology Ltd",
    "Mplx LP",
    "Royal Caribbean Cruises Ltd",
    "Stealthgas",
    "USD Partners LP",
    "Acadia Pharmaceuticals Inc",
    "Neuralstem",
    "Allot Communications Ltd",
    "Safe Bulkers Inc",
    "Can-Fite Biopharma Ltd Sponsore",
    "Insmed Inc",
    "Customers Bancorp",
    "Ngl Energy Partners LP",
    "Tripadvisor Inc",
    "Soufun Holdings",
    "Formfactor",
    "Advanced Energy Industries",
    "Powersecure International Inc",
    "Liberty Tripadvisor Holdings I",
    "Retractable Technologies",
    "Travelcenters of America Llc",
    "Nustar Energy L.P.",
    "Isle of Capri Casinos",
    "Equity Midstream Partners LP",
    "Hi-Crush Partners LP",
    "Gran Tierra Energy Inc",
    "Targa Resources",
    "Straight Path Communications In",
    "Golar Lng Limited",
    "Lrr Energy L.P.",
    "Teekay Tankers Ltd",
    "The Exone Company",
    "Smart",
    "King Digital Entertainment Plc",
    "Synergy Resources Cp",
    "Hydrogenics Corp",
    "Dcp Midstream Partners LP",
    "Buckeye Partners L.P.",
    "Rocket Fuel Inc.",
    "Audiovox Corp",
    "Clayton Williams Energy",
    "Qunar Cayman Islands Limited",
    "Comscore Inc",
    "Delek US Holdings",
    "Sizmek Inc.",
    "Cyberark Software Ltd.",
    "Whiting USA Trust II",
    "Cheniere Energy Partners LP",
    "Himax Technologies",
    "AK Steel Holding Corp",
    "National Bank of Greece Sa",
    "Rada Electronics Industries Limited",
    "Just Energy Group Inc",
    "World Wrestling Entertainment",
    "Ballard Power Systems",
    "Niska Gas Storage Partners Llc",
    "Richmont Mines",
    "Alliance Fiber Optic Products",
    "Tekmira Pharmaceuticals Corp",
    "JA Solar Holdings Co.",
    "Polypore International Inc",
    "Nuvasive Inc",
    "Mellanox Technologies",
    "Svb Financial Group",
    "Bluebird Bio Inc",
    "Canadian Solar Inc",
    "Marathon Petroleum Corp",
    "Methode Electronics",
    "NPS Pharmaceuticals",
    "Viewpoint Financial Group",
    "Abengoa Yield Plc",
    "Orexigen Therapeutics",
    "Yingli Green Energy Holding Company",
    "Transocean Partners Llc",
    "Sanmina-Sci Corp",
    "Pacific Biosciences of California",
    "PBF Energy Inc",
    "Antares Pharma",
    "Crestwood Midstream Partners LP",
    "Graftech International Ltd",
    "Emerge Energy Services LP Commo",
    "Atlas Resource Partners L.P. C",
    "Entravision Communications Corp",
    "Pembina Pipeline Cor",
    "Sanderson Farms",
    "Hong Kong Highpower Technology",
    "Orasure Technologies",
    "Acxiom Corp",
    "Wesco Aircraft Holdings Inc",
    "Southcross Energy Partners L.",
    "Cytokinetics Inc",
    "Penn National Gaming",
    "Novavax Inc",
    "Synergy Pharmaceuticals Inc",
    "Flexion Therapeutics Inc",
    "Amerigas Partners L.P.",
    "E-House [China] Holdings",
    "Aegerion Pharmaceuticals",
    "Futurefuel Corp",
    "Maxwell Technologies",
    "Rubicon Technology",
    "Voc Energy Trust",
    "Ocean Rig Udw Inc",
    "Lee Enterprises Inc",
    "Nustar Gp Holdings Llc",
    "Anacor Pharmaceuticals",
    "Tidewater Inc",
    "Jakks Pacific",
    "Ophthotech Corp",
    "Quantum Fuel Systems Technologies",
    "Xcerra Corp.",
    "Delek Logistics Partners LP",
    "Saia Inc",
    "Celldex Therapeutics Inc",
    "Weatherford International Ltd",
    "Willbros Group",
    "Jinkosolar Holding Company Limited",
    "Audience Inc",
    "Energy Recovery",
    "Itt Educational Services",
    "Theravance Biopharma Inc.",
    "Carbo Ceramics",
    "Harvest Natural Resources Inc",
    "Solazyme Inc",
    "Mid-Con Energy Partners LP"
]